### ISSUE TITLE
Invite codes should not be versioned and visible.

### ISSUE THREAD

**Issue by Alpha-Directorate** [Alpha-Directorate/AlphaSSS#2]
Currently, the new-member invite codes reside in the file: `content/plugins/alpha-hooks/includes/invitation-codes.php`. Obviously, this isn't right. The codes should not be visible to the public at large.

Need a short-term solution to hide this information. For now, only one test code is available stored in an array. The inviter is a fictitious member, user name `Alexis`. (A user I made up on my local environment.)

Long term solution: The invitation system needs to be revamped (probably using the "Invite Anyone" plugin.)

**Comment by Andrew-Voyticky** [comment]
This issue is not relevant any more.
Creating new set of requirements.
